# Generated by Django 2.0 on 2017-12-22 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('email', models.CharField(max_length=40)),
                ('post_method', models.CharField(choices=[('7-11店到店', '7-11店到店'), ('郵局', '郵局')], default='7-11店到店', max_length=10)),
                ('store_name', models.CharField(blank=True, max_length=40)),
                ('store_No', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(max_length=40)),
                ('bank', models.CharField(choices=[('郵局', '郵局'), ('台灣銀行', '台灣銀行'), ('彰化銀行', '彰化銀行')], default='郵局', max_length=10)),
                ('last_5_digits', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('is_agree', models.BooleanField(max_length=2)),
                ('order_id_number', models.CharField(default='23062E820A', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('PaymentNotice', models.BooleanField(default='False', max_length=2)),
                ('PaymentReceived', models.BooleanField(default='False', max_length=2)),
                ('Ordered', models.BooleanField(default='False', max_length=2)),
                ('OrderReceivedUSA', models.BooleanField(default='False', max_length=2)),
                ('ShippingFee', models.BooleanField(default='False', max_length=2)),
                ('PackageDeliveredTW', models.BooleanField(default='False', max_length=2)),
                ('Sent', models.BooleanField(default='False', max_length=2)),
                ('TraceNo', models.CharField(blank=True, default='', max_length=100)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buying.Order')),
            ],
        ),
    ]
