# Generated by Django 2.0 on 2017-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0002_auto_20171223_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id_number',
            field=models.CharField(default='2205E1D589', max_length=256),
        ),
        migrations.AlterField(
            model_name='orderall',
            name='order_id_number',
            field=models.CharField(default='2205E403A1', max_length=256, primary_key=True, serialize=False),
        ),
    ]
