# Generated by Django 2.0 on 2017-12-24 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buying', '0003_auto_20171223_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=15)),
                ('average_price', models.FloatField()),
                ('last_price', models.FloatField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('recent_sell', models.DateField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('add_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id_number',
            field=models.CharField(default='895EA5E2C', max_length=256),
        ),
        migrations.AlterField(
            model_name='orderall',
            name='order_id_number',
            field=models.CharField(default='895F40333', max_length=256, primary_key=True, serialize=False),
        ),
    ]
