# Generated by Django 2.0 on 2017-12-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0004_auto_20171224_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id_number',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='orderall',
            name='order_id_number',
            field=models.CharField(default='23156ABBE5', max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buying.Order'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
