# Generated by Django 2.0 on 2017-12-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0007_auto_20171224_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderall',
            name='order_id_number',
            field=models.CharField(default='262238301A', max_length=256, primary_key=True, serialize=False),
        ),
    ]
