# Generated by Django 2.0 on 2017-12-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0009_auto_20171224_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderall',
            name='order_id_number',
            field=models.CharField(default='2895102278', max_length=256, primary_key=True, serialize=False),
        ),
    ]
