# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-25 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0010_auto_20171224_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='add_people',
        ),
        migrations.DeleteModel(
            name='OrderAll',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
