# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-26 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0011_auto_20171225_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.CharField(choices=[('郵局', '郵局'), ('台灣銀行', '台灣銀行'), ('彰化銀行', '彰化銀行')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='facebook',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_method',
            field=models.CharField(choices=[('7-11店到店', '7-11店到店'), ('郵局', '郵局')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_No',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
